### PR TITLE
Challenge1 branch

### PR DESCRIPTION
**Pull request by acarolinaocosta**
Heey,
Follow my pull request for the first challenge

### CODE REVIEW

**Review by srdjadzogaz — COMMENTED** [review]
Anna you should not commit node modules. 
What needs to be done is to add .gitignore file and add node_modules folder to the ignore list. We do not want to upload node modules to the github.

**Comment by acarolinaocosta** [comment]
Hi, I did the commit again, and I took off the node_modules folder

**Review by srdjadzogaz — COMMENTED** [review]
Please add following to the .gitignore file
node_modules

This will ignore node modules in the future. 

Also run `npm i prompt-sync`
This will add prompt sync for the package.json file which is required. 
After that commit and we should be good

**Comment by srdjadzogaz** [comment]
Very good, congrats! 🥳 🥳 🥳

**Review by srdjadzogaz — APPROVED** [review]

**Pull request merged**
